docs: Refactor QS section
KubeRocketCI/docs pull request #7
Opened 2024-07-03 09:38 UTC by Rolika4

* Update sonar part of Quick Start guide

2024-07-03 14:01 UTC, SergK requested changes
please address the same things for 3.9.0 version

2024-07-03 14:01 UTC, SergK commented on docs/quick-start/platform-installation.md
>    * Default namespace: `edp`
do we need to align 68, 69?

2024-07-03 16:09 UTC, Rolika4 commented on docs/quick-start/platform-installation.md
>    * Default namespace: `edp`
aligned

2024-07-04 17:35 UTC, SergK approved these changes

2024-07-04 17:35 UTC, merged